# Multivarient Technique

# 1.KNN

In [22]:
import numpy as np
import pandas as pd 

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score

In [23]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [35]:
df

      Age  Pclass     Fare  Survived
0    22.0       3   7.2500         0
1    38.0       1  71.2833         1
2    26.0       3   7.9250         1
3    35.0       1  53.1000         1
4    35.0       3   8.0500         0
..    ...     ...      ...       ...
886  27.0       2  13.0000         0
887  19.0       1  30.0000         1
888   NaN       3  23.4500         0
889  26.0       1  30.0000         1
890  32.0       3   7.7500         0

[891 rows x 4 columns]

In [25]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [26]:
X = df.drop(columns=['Survived'])
y=df['Survived']

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [36]:
X_train

      Age  Pclass      Fare
30   40.0       1   27.7208
10    4.0       3   16.7000
873  47.0       3    9.0000
182   9.0       3   31.3875
876  20.0       3    9.8458
..    ...     ...       ...
534  30.0       3    8.6625
584   NaN       3    8.7125
493  71.0       1   49.5042
527   NaN       1  221.7792
168   NaN       1   25.9250

[712 rows x 3 columns]

In [29]:
y_train

30     0
10     1
873    0
182    0
876    0
      ..
534    0
584    0
493    0
527    0
168    0
Name: Survived, Length: 712, dtype: int64

In [48]:
knn = KNNImputer(n_neighbors=10,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [49]:
X_train_trf

array([[ 40.        ,   1.        ,  27.7208    ],
       [  4.        ,   3.        ,  16.7       ],
       [ 47.        ,   3.        ,   9.        ],
       ...,
       [ 71.        ,   1.        ,  49.5042    ],
       [ 31.12515533,   1.        , 221.7792    ],
       [ 49.07622319,   1.        ,  25.925     ]], shape=(712, 3))

In [50]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  24.278772     3.0    8.7125
709  71.000000     1.0   49.5042
710  31.125155     1.0  221.7792
711  49.076223     1.0   25.9250

[712 rows x 3 columns]

In [51]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397